version: '3.8'
services:
  db:
    image: mysql/mysql-server
    restart: always
    environment:
      MYSQL_DATABASE: 'mydb'
      MYSQL_USER: 'dbuser'
      MYSQL_PASSWORD: 'helloDEV222_'
      #for root access
      MYSQL_ROOT_PASSWORD: 'helloDEV222_'
      MYSQL_ROOT_HOST: '10.1.0.4'
      MYSQL_USER_HOST: '10.1.0.4'
    ports:
      #running inside container
      - '3306'
    networks:
      product-network:
        ipv4_address: 172.24.0.12
    volumes:
      - ./mysqldump:/docker-entrypoint-initdb.d/

  backend:
    depends_on:
      - db
    build:
      context: ../Products-Backend/
    restart: unless-stopped
    # env_file: ./.env
    expose:
      - 5000
    # environment:
    #   - DB_HOST=db
    #   - DB_USER=$USER
    #   - DB_PASSWORD=$PASSWORD
    #   - DB_NAME=$DB
    #   - DB_PORT=$MYSQLDB_DOCKER_PORT
    networks:
      product-network:
        ipv4_address: 172.24.0.11

networks:
  product-network:
    # external: true
    name: products-network
    ipam:
      config:
        - subnet: 172.24.0.0/16