version: '3.8'
services:
  db:
    image: mysql/mysql-server
    restart: always
    environment:
      MYSQL_DATABASE: 'mydb'
      MYSQL_USER: 'dbuser'
      MYSQL_PASSWORD: 'helloDEV222_'
      #for root access
      MYSQL_ROOT_PASSWORD: 'helloDEV222_'
      MYSQL_ROOT_HOST: '10.1.0.4'
      MYSQL_USER_HOST: '10.1.0.4'
    ports:
      #running inside container
      - '3306'
    networks:
      product-network:
        ipv4_address: 172.24.0.12
    volumes:
      - ./mysqldump:/docker-entrypoint-initdb.d/

  backend:
    depends_on:
      - db
    build:
      context: ../Products-Backend/
    restart: unless-stopped
    env_file: ./.env
    expose:
      - 5000
    # environment:
    #   - HOST=db
    #   - USER=dbuser
    #   - PASSWORD=helloDEV222_
    #   - DB=mydb
    #   - DIALECT=mysql
    #   - POOL_MAX=5
    #   - POOL_MIN=0
    #   - POOL_ACCUIRE=30000
    #   - POOL_IDLE=10000
    networks:
      product-network:
        ipv4_address: 172.24.0.11

networks:
  product-network:
    # external: true
    name: products-network
    ipam:
      config:
        - subnet: 172.24.0.0/16