version: '3.3'
services:
  db:
    image: mysql/mysql-server
    restart: always
    environment:
      MYSQL_DATABASE: 'mydb'
      MYSQL_USER: 'dbuser'
      MYSQL_PASSWORD: 'helloDEV222_'
      #for root access
      MYSQL_ROOT_PASSWORD: 'helloDEV222_'
      MYSQL_ROOT_HOST: '10.1.0.4'
      MYSQL_USER_HOST: '10.1.0.4'
    ports:
      #running inside container
      - '3306'

    volumes:
      - ./mysqldump:/docker-entrypoint-initdb.d/